title: Moritz Bley
logo: /assets/img/logo.png
github:
  is_user_page: false
description: Personal webpage of Moritz Bley - publications and contact information.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
